// <auto-generated />
using System;
using AiNavigator.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiNavigator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiNavigator.Api.Entities.RequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AiNavigator.Api.Entities.RequestHistory", b =>
                {
                    b.OwnsOne("AiNavigator.Api.Dtos.PromptDetailsDto", "Details", b1 =>
                        {
                            b1.Property<int>("RequestHistoryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Category")
                                .HasColumnType("integer")
                                .HasColumnName("Category");

                            b1.Property<string>("Cons")
                                .HasColumnType("text")
                                .HasColumnName("Cons");

                            b1.Property<string>("GeneralSummary")
                                .HasColumnType("text")
                                .HasColumnName("GeneralSummary");

                            b1.Property<string>("Link")
                                .HasColumnType("text")
                                .HasColumnName("Link");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.Property<string>("Pros")
                                .HasColumnType("text")
                                .HasColumnName("Pros");

                            b1.Property<string>("QueryDate")
                                .HasColumnType("text")
                                .HasColumnName("QueryDate");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("Rank");

                            b1.Property<string>("ShortDescription")
                                .HasColumnType("text")
                                .HasColumnName("ShortDescription");

                            b1.HasKey("RequestHistoryId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("RequestHistoryId");
                        });

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
